name: Project tests
on:
  push:
    branches:
      - main
      - develop
      - testing
  pull_request:
    branches:
      - main
      - develop
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run:  | 
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Pylint
        run: pylint src/
      - name: Test with pytest
        run:  pytest -vv
      - name: Mypy
        run:  mypy src/
      - name: Coverage
        run:  coverage report -m
      - name: Safety check
        run:  safety check -r requirements.txt
      - name: Bandit check
        run:  bandit -r src
      - name: Dead Code
        run:  dead --exclude tests/ 
      - name: Documentation coverage check
        run:  interrogate -vv -I src
      - name: Pydocstyle
        run:  pydocstyle src/

