name: Project tests
on:
  push:
    branches:
      - main
      - develop
      - testing
  pull_request:
    branches:
      - main
      - develop
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run:  pytest -vv